name: API tests

on:
    pull_request:

jobs:
    apicurltests:
        strategy:
            matrix:
                php-version: [ '7.2', '8.0' ]
        name: curl tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: shivammathur/setup-php@v2
              with:
                  # test the lowest version, to make sure checks pass on it
                  php-version: ${{ matrix.php-version }}
                  extensions: json, mbstring, pdo, curl, pdo_sqlite
                  coverage: none
            - name: Initialise
              run: |
                  wget https://get.symfony.com/cli/installer -O - | bash
                  export PATH="$HOME/.symfony5/bin:$PATH"
                  symfony composer self-update -q	
            - name: Install dependencies
              run: |
                  export PATH="$HOME/.symfony5/bin:$PATH"
                  COMPOSER_MEMORY_LIMIT=-1 COMPOSER_PROCESS_TIMEOUT=60 symfony composer update --prefer-dist --no-progress
            - name: Initialise the database
              run: |
                  export PATH="$HOME/.symfony5/bin:$PATH"
                  chmod -R 777 config/ public/files/ public/theme/ public/thumbs/ var/
                  symfony console doctrine:database:create
                  symfony console doctrine:schema:create
                  symfony server:start --no-tls --port=8088 -d
            - name: create api user
              run: |
                  export PATH="$HOME/.symfony5/bin:$PATH"
                  symfony console bolt:add-user apiuser apiuser%1 api@example.org API --roles=ROLE_WEBSERVICE
            - name: check API user gets content
              run: curl -fkI -u apiuser:apiuser%1 http://localhost:8088/api/contents
            - name: check API user gets fields
              run: curl -fkI -u apiuser:apiuser%1 http://localhost:8088/api/fields
            - name: check API user gets relations
              run: curl -fkI -u apiuser:apiuser%1 http://localhost:8088/api/relations
